### ISSUE TITLE
Email suggestions from John Levine

### ISSUE THREAD

**Issue by larseggert** [larseggert/moderation#27]
[Email suggestions](https://mailarchive.ietf.org/arch/msg/gendispatch/2H9subWDn6IRvkXAPhCT54PF6d8) from John Levine:
```
While I think the idea of this draft is fine, I do not understand the 2119 language.

In other RFCs, 2119 language tells you how to interoperate.  You MUST do this or
your system won't interoperate with others.  But here, for example:

 This IETF moderator team ... SHALL moderate all the IETF's various
 current and future participation channels. 

I hope they do, but if they don't, what happens? It starts an appeal?
The moderators are fired? The IETF sinks further into chaos? 

I'd replace the 2119 stuff with normal English or else replace the
boilerplate paragraph 2 with an explanation of what SHALL, MUST NOT,
etc. mean in this context.
```

**Comment by larseggert** [comment]
I think the 2119 language adds clarity, but I could be convinced to lowercase.

**Comment by becarpenter** [comment]
It's a general problem with process documents, because 2119 was really aimed at technical specs. Maybe this document can set a precedent - define its own terminology text instead of citing RFC2119/8174:

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
document are to be interpreted  in their normal English sense; they are shown
in uppercase for emphasis and clarity.

**Comment by larseggert** [comment]
@becarpenter would you prepare a PR so we can see how that would look like?

**Comment by becarpenter** [comment]
PR just sent
